### ISSUE TITLE
Add SQL training

### ISSUE THREAD

**Issue by nicorafales** [tighten/onramp#52]
W3Schools is a great resource for basic (and not so) SQL queries and what is it all about. Without overwhelming theory.

https://www.w3schools.com/sql/

I'd place it under the CSS section since one I/O device is the web, another can be CLI, and the other is for sure the database. It's better to have some understanding of it.
Besides, it makes you think on a declarative language which is how we want Laravel to be, it forms your brain into asking the computer what do you need instead of trying to make the computer do something.

**Comment by Treggats** [comment]
I agree that SQL is valuable knowledge. But I wonder if it is in the scope of onramp.
Since we use Eloquent as ORM which abstracts a lot of SQL and we would only go for raw SQL when we need to do more complicated stuff.

I'm not against it, don't get me wrong. But at the moment I'm not sure where this would fit.
Maybe we can have some kind of 'extra' or 'advanced' topics where SQL would fit.

**Comment by mattstauffer** [comment]
I think it might make the most sense to have a basic intro to how relational databases work, rather than knowing how to write raw SQL?

**Comment by Treggats** [comment]
That would make sense, a global overview how a database works.
Also, we're targeting devs coming from WP right? Wouldn't they already know SQL/database concepts?

**Comment by mattstauffer** [comment]
Nope, we're targeting three tracks:

1. People who are learning coding for the first time
2. Frontend devs and recent frontend bootcamp grads
3. WordPress devs

**Comment by TammyTee** [comment]
Closing now that we have the [SQL and Databases](https://onramp.dev/en/modules/sql-and-databases/free-resources) module.

@nicorafales Thank you for this suggestion! We would be happy to hear if you have ideas for resources you would like to see in this module 😄.
